services:
  redis:
    image: redis/redis-stack:7.2.0-v6
    restart: always
    ports:
      - 6379:6379
    environment:
      REDIS_ARGS: >
        --requirepass 123456 
        --user rediser on >123456 ~* &* +@all 
        --user default off nopass resetchannels -@all

  postgres:
    image: postgres:15.5
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: postgres

  jaeger-all-in-one:
    image: jaegertracing/all-in-one:1.52.0
    restart: always
    ports:
      - "16686:16686"
      - "14268:14268"
      - "14250:14250"

  zipkin-all-in-one:
    image: openzipkin/zipkin:2.25.2
    restart: always
    ports:
      - "9411:9411"

  prometheus:
    image: prom/prometheus:v2.48.1
    restart: always
    volumes:
      - ./otel/prometheus.yaml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"

  grafana:
    container_name: grafana
    image: grafana/grafana:10.2.3
    environment:
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: 123456
      GF_INSTALL_PLUGINS: redis-datasource
    volumes:
      - ./otel/grafana-datasources.yaml:/etc/grafana/provisioning/datasources/datasources.yaml
    ports:
      - "3000:3000"
    depends_on:
      - prometheus
      - jaeger-all-in-one
      - zipkin-all-in-one

  otel-collector:
    image: otel/opentelemetry-collector-contrib:0.91.0
    restart: always
    command: [ "--config=/etc/otel-collector-config.yaml" ]
    volumes:
      - ./otel/otel-collector-config.yaml:/etc/otel-collector-config.yaml
    ports:
      - "4317:4317" # OTLP gRPC port
      - "4318:4318" # OTLP HTTP port
      - "8888:8888" # Prometheus metrics exposed by the collector
      - "8889:8889" # Prometheus exporter metrics
      - "13133:13133" # health_check extension
      - "55679:55679" # zpages extension
      - "1888:1888"   # pprof extension
    depends_on:
      - jaeger-all-in-one
      - zipkin-all-in-one
      - prometheus
      - grafana
