package net.hackertalk.model;

public enum FSAType {
    CHAT_MESSAGE_CREATED,
    CHANNEL_MEMBER_CREATED,
    CHANNEL_MEMBER_UPDATED,
    CHANNEL_MEMBER_DELETED,
    CHANNEL_MESSAGE_CREATED,
    CHANNEL_MESSAGE_UPDATED,
    CHANNEL_MESSAGE_DELETED,
}
